### ISSUE TITLE
Cannot find module '../vendor-manifest.json'

### ISSUE THREAD

**Issue by wangfpp** [areyouse7en/webpack-project#1]
按照你的方法试了一下  但是报错了   这个json文件是干什么用的呢？

**Comment by areyouse7en** [comment]
能贴一下报错吗？按正常步骤安装依赖，npm run dll 再 npm start

json是指哪个？vendor-mainfest吗？这个文件是用来让 DLLReferencePlugin 映射到相关的依赖上去的

**Comment by wangfpp** [comment]
谢谢啊　　我明白怎么回事了　我还有一些疑问
1.使用DllPlugin 确实可是节省打包时间　但是预打包出来的js体积过大
2.类似于这种方法能不能对img　进行预打包呢？　因为这些图片也是不经常变动的(我查资料也没有具体的方法)

**Comment by areyouse7en** [comment]
预打包出来的体积已经是压缩后的了，其实和publish后的一样，这个再过大。。那就是真的大了。。
dllplugin只能对项目依赖做处理，图片不在这个范畴内了。
小图一般走url-loader占不了什么时间和体积，大图建议直接用[工具](https://tinypng.com/)处理后放到static目录下

**Comment by wangfpp** [comment]
我又按照你的方法试了一遍，代码也对照了，每次打包上线的时候　，都会提示预打包的js找不到，不知道什么原因
![default](https://user-images.githubusercontent.com/35289556/36720712-caa5a2a4-1be3-11e8-8545-0c5ab171ad39.jpg)

**Comment by areyouse7en** [comment]
webpack.prod.conf.js里是要写vendorjsname的，你是跑的我这个项目还是照着自己写了一个？

**Comment by areyouse7en** [comment]
不过不用太纠结这个啦，webpack4已出~

**Comment by wangfpp** [comment]
已经解决了，多谢多谢，还解决了hash文件共存的问题,避免产生垃圾
